##
## build context in directory: evita_performance_tests/src/do_k8s_automation/db
##

FROM postgres:14.1

ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="test"
ENV POSTGRES_DB="catalog_testCatalog"

COPY postgresql.conf /tmp/postgresql.conf
